-- ============================================================
-- MintPrompt — Update categories + seed 65 prompts
-- Run in Supabase SQL Editor
-- ============================================================

-- ─── 1. Clear old categories and insert new ones ─────────────
delete from public.categories;

insert into public.categories (name, slug, sort_order) values
  ('Mirror Selfie',          'mirror-selfie',         1),
  ('Old Money',              'old-money',             2),
  ('Streetwear',             'streetwear',            3),
  ('Cafe Aesthetic',         'cafe-aesthetic',        4),
  ('Tokyo Rain',             'tokyo-rain',            5),
  ('Y2K Futuristic',         'y2k-futuristic',        6),
  ('90s Analog Film',        '90s-analog-film',       7),
  ('90s Vintage Yearbook',   '90s-vintage-yearbook',  8),
  ('Acubi/K-Minimalist',     'acubi-k-minimalist',    9),
  ('Gorpcore',               'gorpcore',              10),
  ('Anime Dreamy',           'anime-dreamy',          11),
  ('Golden Hour',            'golden-hour',           12),
  ('Night Flash',            'night-flash',           13);

-- ─── 2. Seed prompts (65 entries, 5 per category) ───────────
-- We use a DO block to resolve category IDs dynamically.

DO $$
DECLARE
  cat_mirror        uuid; cat_oldmoney     uuid; cat_street       uuid;
  cat_cafe          uuid; cat_tokyo        uuid; cat_y2k          uuid;
  cat_analog        uuid; cat_yearbook     uuid; cat_acubi        uuid;
  cat_gorpcore      uuid; cat_anime        uuid; cat_golden       uuid;
  cat_nightflash    uuid;
BEGIN
  SELECT id INTO cat_mirror     FROM public.categories WHERE slug = 'mirror-selfie';
  SELECT id INTO cat_oldmoney   FROM public.categories WHERE slug = 'old-money';
  SELECT id INTO cat_street     FROM public.categories WHERE slug = 'streetwear';
  SELECT id INTO cat_cafe       FROM public.categories WHERE slug = 'cafe-aesthetic';
  SELECT id INTO cat_tokyo      FROM public.categories WHERE slug = 'tokyo-rain';
  SELECT id INTO cat_y2k        FROM public.categories WHERE slug = 'y2k-futuristic';
  SELECT id INTO cat_analog     FROM public.categories WHERE slug = '90s-analog-film';
  SELECT id INTO cat_yearbook   FROM public.categories WHERE slug = '90s-vintage-yearbook';
  SELECT id INTO cat_acubi      FROM public.categories WHERE slug = 'acubi-k-minimalist';
  SELECT id INTO cat_gorpcore   FROM public.categories WHERE slug = 'gorpcore';
  SELECT id INTO cat_anime      FROM public.categories WHERE slug = 'anime-dreamy';
  SELECT id INTO cat_golden     FROM public.categories WHERE slug = 'golden-hour';
  SELECT id INTO cat_nightflash FROM public.categories WHERE slug = 'night-flash';

  -- ── MIRROR SELFIE (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Oversized Hoodie Mirror',
   'oversized-hoodie-mirror',
   'Cozy Gen Z mirror selfie in an oversized vintage-wash hoodie, warm bedroom lighting.',
   cat_mirror,
   ARRAY['mirror','selfie','hoodie','bedroom','cozy'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic Gen Z girl taking a mirror selfie in a cozy bedroom. She wears a faded oversized forest-green hoodie, low-rise jeans, and gold hoop earrings. One hand holds a black iPhone, the other adjusts the hoodie. Soft warm lamp light, fairy lights in background, film-grain texture, candid aesthetic.',
   'A young woman taking a bedroom mirror selfie. Oversized vintage washed hoodie in sage green, relaxed low-rise jeans with a visible belt, layered gold necklaces. Warm tungsten light, slightly soft focus, Gen Z room decor visible in reflection. Photorealistic, natural skin, no filter look.',
   true),

  ('Y2K Crop Mirror Pose',
   'y2k-crop-mirror-pose',
   'Trendy bathroom mirror selfie with Y2K-inspired crop top and low-rise skirt.',
   cat_mirror,
   ARRAY['mirror','y2k','crop','bathroom','trendy'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic teenage girl in a sleek white bathroom taking a mirror selfie. She wears a silver metallic crop top, low-rise micro pleated mini skirt, platform chunky sneakers, and thin silver chain necklace. Phone covers half her face. Bright vanity lighting, glossy tiles reflection, sharp and clean.',
   'Gen Z mirror selfie in a bright minimalist bathroom. Y2K aesthetic: shiny silver crop top, low-rise skirt, platform sneakers visible at bottom of frame. Layered silver jewelry. Crisp white tiles, bright LED mirror lights, clean Instagram-ready composition.',
   true),

  ('Dark Academia Mirror',
   'dark-academia-mirror',
   'Moody full-length mirror selfie in dark academia layers — blazer, turtleneck, plaid.',
   cat_mirror,
   ARRAY['mirror','dark academia','blazer','turtleneck','moody'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic young woman doing a full-length mirror selfie in a dim study room. She wears a fitted brown blazer over a cream turtleneck, plaid high-waisted trousers, leather Oxford shoes, and a delicate pearl necklace. Moody warm candlelight, bookshelves behind, old ornate mirror frame, film grain.',
   'Dark academia mirror selfie. Woman in tailored tweed blazer, ribbed turtleneck, plaid wide-leg trousers, Oxford heels, pearl earrings. Old ornate gold-frame mirror, dimly lit study with warm amber lamp, stack of books visible. Cinematic moody atmosphere.',
   true),

  ('Soft Girl Aesthetic Mirror',
   'soft-girl-aesthetic-mirror',
   'Pastel soft-girl mirror selfie with bow accessories and a fluffy cardigan.',
   cat_mirror,
   ARRAY['mirror','soft girl','pastel','cardigan','bow'],
   ARRAY['gemini','mj']::text[],
   'Photorealistic soft girl aesthetic mirror selfie. Young woman in pastel pink fluffy oversized cardigan, white mini skirt, Mary Jane shoes. Hair in two mini buns with pastel bow clips. Multiple layered necklaces. Cute cluttered room background with plushies and fairy lights. Warm pink-toned lighting.',
   'Dreamy soft girl mirror selfie. Fluffy oversized baby-pink cardigan, white ruffled mini skirt, platform Mary Janes. Bow hair clips in twin buns, dainty layered chains. Room background with cute plushies, pink LED lights, aesthetic posters. Warm, slightly overexposed, dreamy mood.',
   true),

  ('Streetwear Night Mirror',
   'streetwear-night-mirror',
   'Moody late-night bathroom mirror selfie in black streetwear with chain details.',
   cat_mirror,
   ARRAY['mirror','streetwear','black','night','chain'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic Gen Z guy in a late-night bathroom mirror selfie. Black oversized graphic tee tucked into black baggy cargo pants, heavy silver chain necklace, black cap worn backwards, black chunky sneakers. Harsh white vanity light, slightly messy bathroom, moody shadows.',
   'Nighttime mirror selfie. All-black streetwear outfit: graphic oversized tee, baggy cargo pants, thick silver chains, backwards black cap. Harsh LED bathroom lighting casting dramatic shadows. Tile walls, slightly blurry background, gritty urban vibe.',
   true);

  -- ── OLD MONEY (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Cream Linen Old Money',
   'cream-linen-old-money',
   'Effortlessly elegant cream linen set in a sunlit villa terrace — quiet luxury.',
   cat_oldmoney,
   ARRAY['old money','linen','cream','villa','elegant'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic young woman in quiet luxury fashion on a sunlit Mediterranean villa terrace. Cream linen wide-leg trousers, matching linen blazer with gold button details, simple white silk top underneath. Delicate gold thin necklace and small pearl earrings. Hair in a loose low bun. Warm golden sunlight, blurred bougainvillea background.',
   'Old money aesthetic editorial. Woman in perfectly tailored cream linen co-ord: flowy wide-leg pants and structured blazer. Minimal gold jewelry, small pearl studs. Standing on marble villa terrace with sea view blurred background. Natural golden light, effortless sophisticated posture.',
   true),

  ('Polo Club Old Money',
   'polo-club-old-money',
   'Ralph Lauren-inspired polo aesthetic with navy cable-knit and chino trousers.',
   cat_oldmoney,
   ARRAY['old money','polo','navy','cable knit','preppy'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic young man in old money preppy fashion. Navy cable-knit sweater over a white collared Oxford shirt, khaki chino trousers with brown leather belt, brown loafers, silver watch on wrist. Holding a coffee cup. Autumn park background, warm orange bokeh leaves, cinematic moody light.',
   'Old money gentleman aesthetic. Cable-knit navy crewneck over Oxford shirt collar showing, slim chinos, polished leather loafers. Silver slim watch, simple ring. Standing in a leafy estate garden, soft autumn afternoon light, sophisticated and effortless.',
   true),

  ('Equestrian Heritage Look',
   'equestrian-heritage-look',
   'Riding boots and heritage scarf channeling European equestrian old money energy.',
   cat_oldmoney,
   ARRAY['old money','equestrian','boots','scarf','heritage'],
   ARRAY['mj','gemini']::text[],
   'Photorealistic young woman in equestrian-inspired old money fashion. Fitted tan riding breeches, dark green velvet blazer, ivory silk blouse with neck tie, tall brown leather riding boots, and a Hermès-style silk scarf loosely around neck. Standing near vintage stone fence, autumn countryside background.',
   'Equestrian old money editorial. Tan riding trousers, forest green structured blazer, white silk pussy-bow blouse, tall polished riding boots. Silk heritage-print scarf draped at neck. Rural estate background, warm diffused light, film-grain analog feel.',
   true),

  ('Library Study Old Money',
   'library-study-old-money',
   'Intellectual old money aesthetic in a grand private library with leather and tweed.',
   cat_oldmoney,
   ARRAY['old money','library','tweed','leather','intellectual'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic woman in a grand private library with dark mahogany shelves full of leather-bound books. She wears a fitted herringbone tweed midi skirt, cream cashmere turtleneck, and brown leather belt. Thin gold glasses, simple stud earrings, hardcover book in hand. Warm lamplight ambiance.',
   'Old money library scene. Herringbone tweed pencil skirt, soft cashmere turtleneck, slim brown leather belt, kitten heel boots. Reading a leather-bound book in a dim grand library. Warm amber lamp glow, polished wood and brass details, timeless intellectual atmosphere.',
   true),

  ('Coastal Old Money Yacht',
   'coastal-old-money-yacht',
   'Nautical stripe and white linen on a sun-drenched yacht deck — coastal grandmother.',
   cat_oldmoney,
   ARRAY['old money','nautical','yacht','stripe','coastal'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic elegant woman on a luxury yacht deck. White linen wide-leg trousers, navy and white Breton stripe sailor top, gold anchor pendant necklace, white canvas espadrilles. Large woven sunhat. Wind-blown hair, sparkling blue sea background, bright Mediterranean sun, golden hour haze.',
   'Coastal old money yacht aesthetic. Breton stripe navy and white top, white flowy linen trousers, espadrilles, oversized straw hat, gold jewelry. Standing at yacht bow, turquoise water background, bright overexposed sunlight, effortless nautical elegance.',
   true);

  -- ── STREETWEAR (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Baggy Cargo Streetwear',
   'baggy-cargo-streetwear',
   'Oversized streetwear layering with multi-pocket cargo pants and puffer vest.',
   cat_street,
   ARRAY['streetwear','cargo','baggy','puffer','urban'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic Gen Z person in urban streetwear. Olive multi-pocket cargo trousers, black oversized heavyweight tee, black puffer gilet vest layered over, white low-top sneakers. Thick silver chain necklace, black snapback cap. Urban concrete background, graffiti wall, overcast natural light.',
   'Streetwear editorial in urban setting. Olive cargo pants with multiple pockets, oversized black tee, cropped puffer vest, chunky white sneakers. Silver chains, black cap. Gray concrete underpass background, flat diffused light, fashion editorial composition.',
   true),

  ('Harajuku Street Style',
   'harajuku-street-style',
   'Colorful layered Harajuku-inspired streetwear with bold patterns and accessories.',
   cat_street,
   ARRAY['streetwear','harajuku','colorful','layers','bold'],
   ARRAY['mj','gemini']::text[],
   'Photorealistic Harajuku-inspired street fashion editorial. Young woman in a layered outfit: bright yellow oversized hoodie, plaid mini skirt over black bike shorts, chunky platform boots, layered colorful socks. Multiple necklaces and charm bracelets, anime character bag. Shibuya street background, dynamic pose.',
   'Harajuku kawaii streetwear. Layered pastel and bright colors: printed hoodie, plaid mini over shorts, platform chunky boots, colorful crew socks pulled up. Accessory stack: chains, charms, bracelets. Tokyo street background with neon signs, vibrant and chaotic energy.',
   true),

  ('Skate Culture Streetwear',
   'skate-culture-streetwear',
   'Classic skate aesthetic with wide-leg pants, graphic tee and quarter-zip fleece.',
   cat_street,
   ARRAY['streetwear','skate','graphic tee','fleece','wide leg'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic skater in street fashion. Wide-leg black denim jeans, white skate-brand graphic tee, grey quarter-zip pullover fleece tied at waist, old-school Vans. Beanie hat, small hoop earrings. Skate park background, golden afternoon sun, casual candid pose.',
   'Skate aesthetic streetwear. Wide-leg jeans, vintage graphic tee, quarter-zip fleece worn open, classic canvas skate shoes. Beanie, simple hoop earrings. Concrete skate park with ramps in background, warm afternoon light, authentic casual vibe.',
   true),

  ('Gorpcore Streetwear Hybrid',
   'gorpcore-streetwear-hybrid',
   'Techwear meets gorpcore: tactical vest over fleece with trail runners.',
   cat_street,
   ARRAY['streetwear','gorpcore','tactical','fleece','trail'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic person in gorpcore-streetwear hybrid fashion. Black tactical multi-pocket vest over thick olive fleece, wide-leg nylon parachute track pants, high-tech trail running shoes. Beanie, reusable water bottle clipped to vest carabiner. Urban forest edge, misty morning light.',
   'Gorpcore streetwear fusion. Tactical vest layered over chunky fleece, nylon parachute cargo trousers, technical trail runners. Beanie, carabiner accessories. Standing at edge of urban forest, cool misty morning atmosphere, muted earth and black tones.',
   true),

  ('Monochrome Black Streetwear',
   'monochrome-black-streetwear',
   'All-black minimalist streetwear — clean silhouettes with subtle texture contrast.',
   cat_street,
   ARRAY['streetwear','black','monochrome','minimalist','clean'],
   ARRAY['gemini','mj']::text[],
   'Photorealistic model in all-black minimalist streetwear. Black oversized bomber jacket, black straight-leg trousers, black ribbed mock-neck top, black chunky lug-sole boots. Silver ring stack and one thin chain. Against a white concrete wall, editorial harsh lighting, high contrast shadows.',
   'All-black streetwear editorial. Oversized black bomber, straight black trousers, fitted mock-neck, black platform boots. Minimal silver jewelry. Clean white concrete background, dramatic studio-like light, strong silhouette focus, luxury streetwear magazine aesthetic.',
   true);

  -- ── CAFE AESTHETIC (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Latte Art Cafe Morning',
   'latte-art-cafe-morning',
   'Cozy morning cafe scene with warm light, a latte, and an oversized knit sweater.',
   cat_cafe,
   ARRAY['cafe','latte','morning','knit','cozy'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic young woman in a cozy European cafe on a quiet morning. Oversized chunky cream knit sweater, high-waisted straight jeans, white sneakers. Both hands wrapped around a ceramic latte cup. Wooden table, warm morning sunlight through condensation-misted window, natural light bokeh.',
   'Cafe aesthetic morning scene. Woman in oversized cable-knit sweater, relaxed high-waist jeans, reading a paperback. Ceramic latte with leaf art on rustic wooden table. Warm diffused window light, wood and terracotta interior, soft and peaceful mood.',
   true),

  ('Parisian Cafe Terrace',
   'parisian-cafe-terrace',
   'Chic Parisian sidewalk cafe in a trench coat with a croissant — effortless chic.',
   cat_cafe,
   ARRAY['cafe','paris','trench coat','croissant','chic'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic chic woman at a Parisian sidewalk cafe terrace. Camel double-breasted trench coat, black turtleneck, slim black trousers, pointed black flats, leather crossbody bag. Croissant on plate, espresso cup. Wrought-iron cafe chairs, blurred tree-lined boulevard in background, golden morning light.',
   'Parisian cafe terrace aesthetic. Tailored camel trench coat, classic black turtleneck, straight-leg black trousers, ballet flats. Sitting with coffee and croissant. Haussmann architecture background, dappled morning sun, effortless French girl editorial.',
   true),

  ('Tokyo Coffee Window Seat',
   'tokyo-coffee-window-seat',
   'Minimalist Tokyo specialty coffee shop — white walls, window light, matcha latte.',
   cat_cafe,
   ARRAY['cafe','tokyo','matcha','window','minimalist'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic person in a minimalist Tokyo coffee shop sitting by a floor-to-ceiling window. Wearing a clean white oversized long-sleeve shirt, straight light-wash jeans, white sneakers. Hands around a matcha latte in a ceramic cup. Concrete and wood interior, pure white walls, diffused northern light.',
   'Tokyo minimalist cafe window seat. Clean oversized white shirt, light straight jeans, simple white sneakers. Matcha latte on bare wood surface. Floor-to-ceiling window with soft natural light, white walls and minimalist Japanese interior design, peaceful atmosphere.',
   true),

  ('Dark Moody Cafe Study',
   'dark-moody-cafe-study',
   'Late night moody cafe with dark walls, dim candlelight, and a leather jacket.',
   cat_cafe,
   ARRAY['cafe','moody','dark','study','leather jacket'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic young person in a dark moody specialty cafe at night. Black leather jacket over grey ribbed turtleneck, dark straight jeans, black boots. Open laptop on dark wood table, espresso shot, dim candlelight casting warm shadows. Dark walls, exposed brick, moody and atmospheric.',
   'Dark moody cafe night scene. Black leather jacket, ribbed grey turtleneck, straight dark jeans. Sitting with open laptop and espresso. Dark-walled atmospheric cafe, flickering candle, warm tungsten glow, brick and dark wood interior, introspective night-study vibe.',
   true),

  ('Hygge Cafe Winter Day',
   'hygge-cafe-winter-day',
   'Danish hygge cafe energy — plaid scarf, thick cardigan, hot cocoa by the window.',
   cat_cafe,
   ARRAY['cafe','hygge','winter','plaid','cardigan'],
   ARRAY['gemini','mj']::text[],
   'Photorealistic cozy winter hygge cafe scene. Young woman in a thick oversized dark green cardigan, plaid flannel scarf loosely draped, relaxed cord trousers, fuzzy socks and loafers. Holding a tall ceramic hot cocoa mug with marshmallows. Frosted window, snow outside, warm amber light inside, peaceful.',
   'Hygge winter cafe aesthetic. Chunky oversized dark green cardigan, plaid scarf, wide corduroy trousers, cozy loafers. Seated by snow-frosted window with hot cocoa. Warm amber lamp, wooden interior with candles, soft blurred snowfall outside, extremely cozy.',
   true);

  -- ── TOKYO RAIN (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Rainy Shibuya Night',
   'rainy-shibuya-night',
   'Cinematic Tokyo rain at night — neon reflections on wet asphalt, transparent umbrella.',
   cat_tokyo,
   ARRAY['tokyo','rain','shibuya','neon','umbrella'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic cinematic scene of a young woman standing in rainy Shibuya at night. Holding a clear transparent umbrella with water droplets. Wearing an oversized black trench coat, black turtleneck, straight black trousers, black Chelsea boots. Colorful neon signs reflecting on wet asphalt below. Cinematic film-still composition.',
   'Cinematic Tokyo rain night. Young woman under clear umbrella at Shibuya crossing. Long black oversized coat, dark fitted layers, Chelsea boots. Vivid neon reflections shimmering on rain-soaked streets. Low-angle shot, rain streaks catching neon light, moody cinematic atmosphere.',
   true),

  ('Convenience Store Rain',
   'convenience-store-rain',
   'Aesthetic Tokyo rain evening — cozy in a convenience store entrance with a onigiri.',
   cat_tokyo,
   ARRAY['tokyo','rain','convenience store','cozy','night'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic Gen Z aesthetic person sheltering in a glowing Tokyo convenience store entrance from rain at night. Wearing a yellow rain jacket unzipped over a white graphic tee, dark grey sweatpants, white sneakers. Holding a triangle onigiri, FamilyMart or Lawson glow behind. Rain on the street, warm interior light.',
   'Tokyo convenience store rain shelter scene. Yellow rain jacket over graphic tee, grey sweatpants, white sneakers. Person eating onigiri under the bright store canopy. Warm fluorescent glow from inside, rain falling on dark street, cozy urban nighttime atmosphere.',
   true),

  ('Quiet Street Rain Walk',
   'quiet-street-rain-walk',
   'Solitary walk down a quiet Tokyo backstreet in the rain — cinematic and melancholic.',
   cat_tokyo,
   ARRAY['tokyo','rain','walking','cinematic','melancholic'],
   ARRAY['mj','flux']::text[],
   'Photorealistic cinematic shot of a lone figure walking down a narrow rain-wet Tokyo backstreet at dusk. Wearing a long olive wax rain jacket, dark slim trousers, rubber Chelsea boots. Earphones in. Paper bag in hand. Traditional wooden buildings and lanterns either side, steam rising from drain, soft rain haze.',
   'Cinematic Tokyo backstreet rain walk. Lone figure in long waxed olive rain jacket, slim dark trousers, rubber boots. Narrow alley with Japanese wooden buildings, paper lanterns, puddles reflecting warm light, gentle rain mist, melancholic and cinematic dusk atmosphere.',
   true),

  ('Train Platform Rain',
   'train-platform-rain',
   'Romantic Tokyo rain — JR train platform in the rain, windows steaming up.',
   cat_tokyo,
   ARRAY['tokyo','rain','train','platform','romantic'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic person standing alone on a wet outdoor Tokyo JR train platform in heavy rain. Wearing a camel oversized coat, dark jeans, white chunky sneakers, light blue knit scarf. Rain streaking down in front of them, train lights approaching, blurred neon in background, emotional atmosphere.',
   'Tokyo rain train platform. Oversized camel coat, knit pale blue scarf, dark jeans, chunky white sneakers. Lone figure on glistening platform, approaching train lights cutting through rain, blurred city neons, heavy rain streaks, cinematic emotional atmosphere.',
   true),

  ('Tokyo Rain Cafe Window',
   'tokyo-rain-cafe-window',
   'Watching Tokyo rain through a steamed cafe window with hot ramen and a grey hoodie.',
   cat_tokyo,
   ARRAY['tokyo','rain','cafe','window','ramen'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic cozy scene of a person sitting inside a small Tokyo ramen shop watching rain outside through a fogged window. Wearing a soft grey oversized hoodie, simple stud earrings. Bowl of steaming ramen on counter. Rain streaking down the window, neon signs blurred outside, warm interior glow.',
   'Tokyo rainy ramen shop window scene. Person in oversized grey hoodie with bowl of steaming ramen. Rain-fogged window with neon blur outside. Narrow counter, warm tungsten light, wooden surfaces, intimate tiny ramen shop atmosphere, cozy and solitary.',
   true);

  -- ── Y2K FUTURISTIC (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Silver Chrome Y2K',
   'silver-chrome-y2k',
   'Full chrome Y2K look with metallic silver co-ord, platform boots, and tinted glasses.',
   cat_y2k,
   ARRAY['y2k','chrome','silver','platform','metallic'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic Y2K futuristic editorial. Young woman in full chrome metallic silver co-ord: silver puffer micro jacket and matching low-rise micro skirt. Platform silver boots, butterfly-frame blue-tinted sunglasses, silver body chain. Background: white studio or glossy futuristic set.',
   'Y2K chrome metallic editorial. Full silver puffer jacket and matching micro skirt set, platform silver boots, tinted butterfly sunglasses, silver chain accessories. Clean futuristic white background, high-key studio lighting, bold fashion magazine composition.',
   true),

  ('Cyber Y2K Street',
   'cyber-y2k-street',
   'Cyber-inspired Y2K street look with transparent accessories and neon accents.',
   cat_y2k,
   ARRAY['y2k','cyber','neon','transparent','futuristic'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic cyber Y2K street fashion. Young person in translucent PVC trench coat over a bright green crop top and baggy black parachute pants. Platform translucent boots, chunky neon-green accessories, black choker. Urban night background with purple and green neon lights.',
   'Cyber Y2K street editorial. PVC transparent trench coat, neon green crop top, baggy parachute pants, platform see-through boots. Neon green chunky accessories, black choker. Urban nighttime background with vibrant neon glow, futuristic city aesthetic.',
   true),

  ('Y2K Denim Butterfly',
   'y2k-denim-butterfly',
   'Low-rise Y2K denim with butterfly clips, platform sneakers, and a sparkle top.',
   cat_y2k,
   ARRAY['y2k','denim','butterfly','sparkle','platform'],
   ARRAY['gemini','mj']::text[],
   'Photorealistic Y2K aesthetic girl in a casual everyday look. Low-rise flare jeans with butterfly stitching, sparkle silver halter top, white platform sneakers. Multiple butterfly clips in straight flat-ironed hair, lip gloss, tiny shoulder bag. Pastel sky background or shopping mall atrium.',
   'Y2K butterfly denim editorial. Low-rise flare jeans, sparkle halter top, platform white sneakers. Hair adorned with colorful butterfly clips, glossy lip, micro bag. Mall or pastel outdoor setting, bright warm light, dreamy Y2K nostalgia energy.',
   true),

  ('Matrix Y2K Black',
   'matrix-y2k-black',
   'Dark futuristic Y2K matrix aesthetic — leather trench, sunglasses, sleek all black.',
   cat_y2k,
   ARRAY['y2k','matrix','leather','trench','dark'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic Matrix-inspired Y2K fashion editorial. Tall young man in a floor-length black PU leather trench coat, black fitted turtleneck, black slim trousers, black pointed ankle boots. Thin rectangle-frame black sunglasses. Moody industrial background, green-tinted dramatic lighting.',
   'Matrix Y2K dark editorial. Long black faux leather trench coat, fitted black turtleneck, slim trousers, pointed boots, rectangle sunglasses. Industrial background, green-tinted dramatic cinematic lighting, strong dark futuristic fashion aesthetic.',
   true),

  ('Y2K Pop Star Pink',
   'y2k-pop-star-pink',
   'Bubblegum pink Y2K pop-star inspired look with rhinestones and micro accessories.',
   cat_y2k,
   ARRAY['y2k','pink','pop star','rhinestone','bubblegum'],
   ARRAY['gemini','flux']::text[],
   'Photorealistic Y2K pop star bubblegum pink aesthetic. Young woman in a hot pink furry crop jacket, matching low-rise cargo micro-shorts, pink platform boots. Rhinestone-encrusted accessories, hoop earrings, pink tinted micro sunglasses. Glittery pink background, pop-art colors.',
   'Y2K pop star editorial. Bubblegum pink fur crop jacket, pink micro cargo shorts, platform boots, rhinestone accessories, tinted pink sunnies. Glitter bomb background, overexposed pop-art energy, iconic Y2K diva aesthetic.',
   true);

  -- ── 90S ANALOG FILM (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('90s Weekend Diner',
   '90s-weekend-diner',
   'Nostalgic 90s analog film look — diner booth, plaid flannel, vintage sneakers.',
   cat_analog,
   ARRAY['90s','analog','diner','flannel','nostalgic'],
   ARRAY['chatgpt','mj']::text[],
   'Analog film photography aesthetic of a young man in a red diner booth. Oversized plaid flannel shirt open over a plain white tee, light wash relaxed jeans, classic white leather sneakers. Milkshake on table. Slightly faded film grain, light leak at corner, 35mm aesthetic.',
   ' 90s analog film diner scene. Plaid flannel over white tee, baggy light jeans, white leather sneakers. Red vinyl booth, chrome diner details, cherry milkshake. Kodak film grain texture, slight overexposure, light leak, nostalgic 90s Saturday afternoon energy.',
   true),

  ('Summer Park Polaroid',
   'summer-park-polaroid',
   'Grainy 90s summer park afternoon — cutoffs, a band tee, and grass stains.',
   cat_analog,
   ARRAY['90s','analog','summer','park','band tee'],
   ARRAY['chatgpt','gemini']::text[],
   'Analog 90s film photo of two friends in a sunny park. One wearing a faded vintage band tee knotted at waist, high-waisted denim cutoff shorts, classic canvas sneakers. Lying on grass, laughing. Heavy film grain, slight color fade, natural summer sunlight overexposure, Fujifilm aesthetic.',
   '90s summer park analog. Knotted vintage band tee, high-waisted denim shorts, canvas shoes. Lying in green grass on a sunny afternoon. Saturated film colors slightly faded, heavy grain, light flare, nostalgic Fujifilm Superia aesthetic.',
   true),

  ('90s Bedroom Portrait',
   '90s-bedroom-portrait',
   'Classic 90s teen bedroom — posters on wall, oversized flannel, disposable camera feel.',
   cat_analog,
   ARRAY['90s','bedroom','portrait','disposable','flannel'],
   ARRAY['chatgpt','grok']::text[],
   'Disposable camera style 90s teen bedroom portrait. Young girl sitting on a bed with band and movie posters on wall behind. Oversized grey band hoodie, plaid flannel as overshirt, ripped straight jeans, chunky sneakers. Strong flash, slightly washed out colors, red-eye effect, authentic 90s disposable camera aesthetic.',
   '90s bedroom disposable cam portrait. Band hoodie, open flannel, ripped jeans, chunky shoes. Sitting on bed, posters and magazine clippings covering walls. Harsh direct flash, washed-out colors, red-eye, grainy texture, perfectly imperfect 90s snapshot energy.',
   true),

  ('Grunge Concert Crowd',
   'grunge-concert-crowd',
   'Film photograph from inside a 90s grunge concert — distressed layers and sweat.',
   cat_analog,
   ARRAY['90s','grunge','concert','distressed','film'],
   ARRAY['mj','flux']::text[],
   'Gritty analog film photo from inside a 90s grunge concert. Young person in distressed black band tee, torn fishnet under ripped jeans, oversized army jacket. In a sweaty crowd, stage light cutting through smoke, people blurred around them. High contrast, strong grain, concert film aesthetic.',
   '90s grunge concert film photo. Distressed band tee, ripped jeans, fishnet, oversized army jacket. In a chaotic concert crowd, hazy stage lights, smoke machine, blurred motion of other fans. High contrast black and white grain, raw gritty energy.',
   true),

  ('Road Trip Window Film',
   'road-trip-window-film',
   'Analog road trip — hand out window, golden summer hour, boyfriend tee.',
   cat_analog,
   ARRAY['90s','road trip','window','golden hour','analog'],
   ARRAY['chatgpt','gemini']::text[],
   'Analog 90s road trip photography. Girl in passenger seat with hand out window against golden sunset highway. Oversized boyfriend tee, denim shorts, bare feet on dashboard. Warm sunset haze through windshield, heavy grain, light leaks on edges, cross-country freedom aesthetic.',
   '90s road trip window shot. Hand stretched out car window into golden sunset. Oversized tee, denim cutoffs. Sun-flared windshield, blurred highway passing. Warm saturated kodachrome film tones, grain, freedom and nostalgia of summer drive.',
   true);

  -- ── 90S VINTAGE YEARBOOK (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Classic School Portrait',
   'classic-school-portrait',
   'Iconic 90s school yearbook portrait with laser background and a denim jacket.',
   cat_yearbook,
   ARRAY['yearbook','portrait','school','denim jacket','90s'],
   ARRAY['chatgpt','mj']::text[],
   'Hyper-realistic 90s school yearbook portrait. Teenage girl in a denim jacket over a striped shirt. Classic laser background in blue and purple gradients. Hair with side part and two small braids. Slight awkward smile, direct camera gaze. Soft studio portrait lighting, authentic yearbook composition.',
   '90s school yearbook portrait. Classic laser gradient blue/purple background. Denim jacket, striped shirt, side-parted hair. Authentic studio yearbook lighting, slightly stiff posture, nostalgic school photo energy, hyper-realistic.',
   true),

  ('Cheerleader Squad Photo',
   'cheerleader-squad-photo',
   'Nostalgic 90s cheerleader team yearbook shot — pleated skirt and letterman energy.',
   cat_yearbook,
   ARRAY['yearbook','cheerleader','squad','letterman','90s'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic 90s high school yearbook cheerleader squad photo. Group of teens in school-color pleated cheerleader skirts and crop tops with letter logo. Arranged in a classic V formation on school bleachers. Big scrunchies, side ponytails, white sneakers. Warm afternoon gym or field light.',
   '90s cheerleader yearbook squad shot. Pleated cheer skirt in school colors, matching crop top, white sneakers, big colorful scrunchies and high ponytails. Classic bleacher background, natural afternoon light, authentic 90s high school energy.',
   true),

  ('Prom Night Portrait',
   'prom-night-portrait',
   'Dreamy 90s prom night — tulle gown, corsage, awkward corsage-pinning moment.',
   cat_yearbook,
   ARRAY['yearbook','prom','tulle','gown','90s'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic 90s prom night yearbook photo. Young couple dressed for prom. Girl in pastel purple tulle ball gown with spaghetti straps, wrist corsage. Boy in classic black tux with matching purple boutonnière. Tacky hotel ballroom background, warm photo studio flash lighting, authentic prom energy.',
   '90s prom night yearbook. Pastel purple tulle gown, wrist corsage, spaghetti straps. Partner in matching tux. Hotel ballroom backdrop, direct flash photography, slight overexposure, authentic embarrassing-in-the-best-way 90s prom aesthetic.',
   true),

  ('Sports Team Huddle',
   'sports-team-huddle',
   'Classic 90s sports yearbook — basketball or football team huddle shot.',
   cat_yearbook,
   ARRAY['yearbook','sports','team','jersey','90s'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic 90s high school sports yearbook photo. Boys basketball team in classic mesh jerseys and matching shorts huddled together on court. Some with sweatbands and high tube socks. Gymnasium background with wooden floor, authentic 90s school sports photo lighting.',
   '90s sports team yearbook huddle shot. Classic mesh basketball jerseys, matching shorts, tube socks pulled high, sneakers. Arms around each other on hardwood gym floor. Authentic 90s school sports photography, direct flash, relaxed team energy.',
   true),

  ('Drama Club Cast Photo',
   'drama-club-cast-photo',
   'Theatrical 90s yearbook drama club cast shot with costumes and stage makeup.',
   cat_yearbook,
   ARRAY['yearbook','drama','theater','cast','90s'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic 90s high school drama club yearbook cast photo. Students in a mix of theatrical costumes on a school stage with velvet curtain backdrop. Exaggerated stage makeup, some in period costumes, theatrical poses. Warm stage lighting, authentic 90s school photo feel.',
   '90s drama club cast yearbook photo. Students in theatrical costumes on stage, velvet curtain background. Stage makeup, dramatic poses, diverse costumes from a school play. Warm stage wash lighting, authentic nostalgic school theatrical energy.',
   true);

  -- ── ACUBI/K-MINIMALIST (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Clean Beige Acubi',
   'clean-beige-acubi',
   'Quiet Korean minimalism — beige, white, and cream tones with clean silhouettes.',
   cat_acubi,
   ARRAY['acubi','korean','minimalist','beige','clean'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic Korean acubi minimalist fashion. Young woman in full beige-toned outfit: oversized structured beige trench coat, cream ribbed knit turtleneck, straight-leg oatmeal trousers, white sock and simple white sneakers. No visible logo. Clean white background or minimalist Seoul apartment.',
   'Acubi Korean minimalist editorial. All-beige and cream tones: structured trench, ribbed knit turtleneck, straight wide trousers, clean white sneakers. Minimal silver jewelry, no logos. White or beige studio background, clean flat lighting, quiet luxury minimal Korean aesthetic.',
   true),

  ('Seoul Street Minimal',
   'seoul-street-minimal',
   'Effortless Seoul street style — navy overcoat, straight trousers, subtle details.',
   cat_acubi,
   ARRAY['acubi','seoul','street','overcoat','minimal'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic Seoul street style minimalist fashion. Young Korean woman in a navy slightly oversized straight-cut overcoat, simple black ribbed top underneath, straight-leg black trousers, white clean sneakers. Silver tiny stud earrings. Clean Seoul street background, cloudy soft flat light.',
   'Seoul minimal street style. Navy oversized overcoat, black ribbed top, straight-leg trousers, clean white sneakers, tiny silver studs. Minimalist Seoul street background, soft diffused overcast light, understated elegant Korean street fashion.',
   true),

  ('K-Minimalist Layers',
   'k-minimalist-layers',
   'Korean minimalism in olive and grey — layered silhouettes and no excess.',
   cat_acubi,
   ARRAY['acubi','layers','olive','grey','minimalist'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic Korean minimalist layered fashion. Young man in an olive long structured vest over a simple grey mock-neck long-sleeve, wide-leg olive-grey trousers, white leather sneakers. Clean composition, minimalist Seoul interior background with white walls and wooden accents.',
   'Korean minimalist layering. Long olive structured vest over grey mock-neck, wide-leg muted trousers, white clean sneakers. No accessories. Minimalist apartment interior background, white and wood, flat even light, quiet effortless Korean fashion.',
   true),

  ('Cafe Uniform Acubi',
   'cafe-uniform-acubi',
   'Aesthetic Korean cafe worker vibes — apron, white shirt, and effortless cool.',
   cat_acubi,
   ARRAY['acubi','cafe','apron','white shirt','korean'],
   ARRAY['gemini','mj']::text[],
   'Photorealistic Korean aesthetic young barista in a minimalist specialty coffee shop. Clean white linen oversized shirt, straight dark trousers, simple white canvas sneakers, dark apron tied at waist. Minimal jewelry. Clean minimal coffee shop background, white walls, wooden counter.',
   'Acubi Korean cafe worker aesthetic. White oversized linen shirt, dark straight trousers, white sneakers, tied apron. Minimal jewelry. Behind a minimalist white and wood specialty coffee counter, natural light, effortless clean Korean cafe energy.',
   true),

  ('White Shirt Coastal Minimal',
   'white-shirt-coastal-minimal',
   'Korean minimalism meets sea air — white oversized shirt, linen trousers, bare feet.',
   cat_acubi,
   ARRAY['acubi','coastal','white','linen','minimal'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic Korean minimalist coastal fashion. Young woman in an oversized crisp white linen shirt worn loose and open over a simple white bralette, straight off-white linen wide-leg trousers, bare feet on pale sand. Minimal gold ear cuff. Korean coastal background, overcast diffused sea light.',
   'Acubi coastal minimal. Oversized white linen shirt open over white bralette, wide-leg linen trousers, bare feet on sand. Single gold ear cuff, no other accessories. Korean coast background, soft grey overcast sea light, quiet effortless minimal beauty.',
   true);

  -- ── GORPCORE (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Alpine Gorpcore Trek',
   'alpine-gorpcore-trek',
   'Technical alpine gorpcore — hardshell jacket, trail runners, and mountain backdrop.',
   cat_gorpcore,
   ARRAY['gorpcore','alpine','hardshell','trail','mountain'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic gorpcore fashion in alpine mountain setting. Young person in a bright orange technical hardshell jacket, mid-layer charcoal fleece visible at collar, nylon trail running shorts, tall hiking gaiters, technical trail runners. Trekking poles, hydration vest. Dramatic rocky alpine peak background.',
   'Alpine gorpcore editorial. Bright orange hardshell shell jacket, fleece mid-layer, nylon shorts, trail runners, gaiters, hydration vest with carabiner. Dramatic rocky mountain summit background, cold crisp light, technical outdoor fashion magazine energy.',
   true),

  ('Urban Gorpcore City',
   'urban-gorpcore-city',
   'Gorpcore meets the city — puffer vest, fleece, cargo trousers, Salomon sneakers.',
   cat_gorpcore,
   ARRAY['gorpcore','urban','puffer','salomon','fleece'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic urban gorpcore street fashion. Young person in a Patagonia-style puffer vest over a thick technical fleece, wide-leg nylon cargo trousers with multiple pockets, Salomon XT trail sneakers. Buff around neck, reusable bottle. Urban city street with trees, overcast flat light.',
   'Urban gorpcore. Puffer vest over technical fleece, wide-leg nylon cargos, Salomon trail sneakers, neck buff, water bottle. City street background with autumn trees, flat overcast light, premium outdoor-meets-street editorial look.',
   true),

  ('Forest Gorpcore Fog',
   'forest-gorpcore-fog',
   'Misty forest gorpcore — earthy tones, waterproof layers, and morning fog.',
   cat_gorpcore,
   ARRAY['gorpcore','forest','fog','earthy','waterproof'],
   ARRAY['mj','flux']::text[],
   'Photorealistic gorpcore fashion in a misty forest at dawn. Person in earth-tone waterproof smock jacket, sage green fleece pullover, brown technical wide trousers, rubber trail boots. Forest background with dense fog and filtered morning light between trees.',
   'Misty forest gorpcore dawn. Waterproof earth-tone smock jacket, sage fleece, brown technical trousers, rubber boots. Dense foggy forest background, diffused cold morning light, muted green and brown palette, quiet and atmospheric outdoor fashion.',
   true),

  ('Ski Town Gorpcore',
   'ski-town-gorpcore',
   'Après-ski gorpcore in a cozy mountain town — ski pants, a beanie, and layers.',
   cat_gorpcore,
   ARRAY['gorpcore','ski','apres','beanie','mountain town'],
   ARRAY['chatgpt','grok']::text[],
   'Photorealistic gorpcore fashion in a snowy ski town main street. Person in bright blue technical ski pants, oversized cream puffer jacket, colorful beanie with pom, technical mid-layers peeking out. Ski boots or snow boots. Quaint snowy mountain town with pine trees and light snowfall.',
   'Ski town gorpcore après-ski. Bright blue technical ski pants, oversized cream puffer, colorful pom beanie, stacked base and mid layers. Snowy alpine village background, warm golden late afternoon ski-day light, premium outdoor street style.',
   true),

  ('Desert Gorpcore Hike',
   'desert-gorpcore-hike',
   'Desert gorpcore — sun hoody, nylon shorts, trail runners on red rock terrain.',
   cat_gorpcore,
   ARRAY['gorpcore','desert','sun hoody','red rock','hiking'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic desert gorpcore fashion. Person in a lightweight sand-color technical sun hoody, quick-dry nylon shorts, trail running shoes with toe guard, lightweight hydration pack. Sunglasses with side shields. Dramatic red rock desert canyon background, harsh midday sun.',
   'Desert gorpcore editorial. Sand technical sun hoody, nylon shorts, technical trail runners, hydration pack. Technical sunglasses. Dramatic red sandstone canyon background, harsh desert midday sun, earth and orange tones, functional performance aesthetic.',
   true);

  -- ── ANIME DREAMY (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Cherry Blossom Uniform',
   'cherry-blossom-uniform',
   'Dreamy anime school uniform under cherry blossoms — sakura petals falling.',
   cat_anime,
   ARRAY['anime','sakura','uniform','dreamy','spring'],
   ARRAY['chatgpt','mj']::text[],
   'Anime-style photorealistic illustration of a high school girl in a classic Japanese school uniform (navy sailor top, pleated skirt) standing under a full cherry blossom tree. Soft sakura petals drifting down. Warm pink-white spring light, dreamy soft focus, slightly cel-shaded, detailed fabric folds.',
   'Dreamy anime cherry blossom school scene. Girl in classic sailor uniform, pleated skirt, under falling sakura petals. Soft ethereal spring light, pink bokeh petals, gentle warm haze, anime-style detailed illustration with photorealistic texture.',
   true),

  ('Starry Night Rooftop',
   'starry-night-rooftop',
   'Anime-dreamy rooftop at night under a vivid starry sky — oversized cardigan.',
   cat_anime,
   ARRAY['anime','rooftop','stars','night','cardigan'],
   ARRAY['gemini','flux']::text[],
   'Anime-style photorealistic illustration of a girl sitting on a rooftop at night, hugging her knees, looking up at a vivid milky way sky. She wears an oversized soft lilac knit cardigan, white dress shirt underneath, knee socks, mary jane shoes. City lights below, ethereal dreamy atmosphere.',
   'Anime dreamy rooftop stargazing. Girl in oversized lilac cardigan, white shirt, knee socks, seated on rooftop edge. Vivid milky way stretching above, warm city lights below, magical dreamy atmosphere, soft cel-shaded illustration style with photorealistic quality.',
   true),

  ('Rain Window Melancholy',
   'rain-window-melancholy',
   'Dreamy anime rainy window moment — quiet melancholy and a yellow raincoat.',
   cat_anime,
   ARRAY['anime','rain','window','melancholy','raincoat'],
   ARRAY['chatgpt','gemini']::text[],
   'Anime-style photorealistic illustration. A girl pressed against a rain-streaked school window, forehead touching the glass, watching rain outside. Wearing yellow hooded raincoat over school uniform, hair slightly damp. Inside warm, outside grey and rainy. Melancholic dreamy mood.',
   'Anime melancholy rainy window. Girl in yellow raincoat forehead pressed to rain-streaked glass. Warm soft interior, grey rainy outside, detailed rain droplets on window. Emotional anime illustration style, cinematic quiet sadness.',
   true),

  ('Summer Festival Yukata',
   'summer-festival-yukata',
   'Vibrant summer anime festival night — yukata, lanterns, fireworks above.',
   cat_anime,
   ARRAY['anime','festival','yukata','lanterns','fireworks'],
   ARRAY['chatgpt','mj']::text[],
   'Anime-style photorealistic illustration of a girl in a beautiful blue and white floral yukata at a summer Matsuri festival at night. Colorful paper lanterns strung above, fireworks bursting in the sky. Hair in updo with kanzashi ornament. Warm festive glow, lively crowd blurred in background.',
   'Anime summer festival yukata scene. Blue floral yukata, hair updo with kanzashi, at a lantern-lit Matsuri. Fireworks exploding overhead, warm orange lantern glow, festive crowd in background, magical dreamy summer anime atmosphere.',
   true),

  ('Misty Morning Forest Walk',
   'misty-morning-forest-walk',
   'Ethereal anime forest walk in morning mist — white dress and wildflowers.',
   cat_anime,
   ARRAY['anime','forest','misty','morning','ethereal'],
   ARRAY['gemini','mj']::text[],
   'Anime-style photorealistic illustration of a girl walking through a misty ancient forest in early morning. Wearing a flowing white sun dress, simple white sandals, wildflowers in loose hair. Soft shafts of light cutting through fog between tall trees. Ethereal, magical, Studio Ghibli-inspired mood.',
   'Anime ethereal forest morning. Girl in flowing white dress, flowers in loose hair, walking barefoot through misty ancient forest. Golden morning light rays through fog, deep green forest, Ghibli-inspired magical nature atmosphere, dreamy and serene.',
   true);

  -- ── GOLDEN HOUR (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Rooftop Sunset Hour',
   'rooftop-sunset-hour',
   'Cinematic golden hour on a city rooftop — warm backlight and summer clothes.',
   cat_golden,
   ARRAY['golden hour','rooftop','sunset','cinematic','warm'],
   ARRAY['chatgpt','mj']::text[],
   'Photorealistic cinematic golden hour editorial on a city rooftop. Young woman backlit by intense orange sunset. Sheer linen white blouse, wide-leg cream trousers, simple gold jewelry, barefoot. Rim light turning edges gold, city skyline silhouette behind, long shadow on rooftop, cinematic magazine shot.',
   'Golden hour rooftop cinematic editorial. Woman in sheer linen blouse and wide-leg trousers backlit by blazing sunset. Warm orange rim light, gold-toned silhouette, blurred city skyline, long shadows, iconic golden hour fashion photography.',
   true),

  ('Meadow Wildflower Walk',
   'meadow-wildflower-walk',
   'Golden hour in a wildflower meadow — flowy dress, warm backlighting, freedom.',
   cat_golden,
   ARRAY['golden hour','meadow','wildflower','flowy','freedom'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic golden hour fashion in an open wildflower meadow. Young woman in a flowy maxi sundress in warm terracotta, loosely braided hair, leather sandals, simple delicate gold ankle bracelet. Backlit by warm golden setting sun, wildflowers in foreground, cinematic freedom aesthetic.',
   'Golden hour meadow fashion. Flowy terracotta maxi dress, loose braid, leather sandals, gold ankle bracelet. Standing in wildflower meadow, warm backlit sunset, foreground flowers slightly blurred, cinematic glowing romantic mood.',
   true),

  ('Convertible Golden Road',
   'convertible-golden-road',
   'Road trip in a convertible at golden hour — hair flying, denim jacket, freedom.',
   cat_golden,
   ARRAY['golden hour','road trip','convertible','denim jacket','freedom'],
   ARRAY['chatgpt','flux']::text[],
   'Photorealistic cinematic shot inside a convertible car at golden hour. Woman in passenger seat, head back, hair flying in warm wind. Denim jacket over white tee, vintage sunglasses. Blurred golden highway and desert scrub passing at speed. Pure cinematic freedom, Lana Del Rey aesthetic.',
   'Golden hour convertible freedom. Woman with hair flying, head tilted back, vintage sunglasses, denim jacket, white tee. Passenger seat, blurred golden desert highway rushing past. Warm glowing light, cinematic motion blur, road trip nostalgia and freedom.',
   true),

  ('Golden Beach Walk',
   'golden-beach-walk',
   'Glowing golden hour along a deserted beach — white linen and bare feet in sand.',
   cat_golden,
   ARRAY['golden hour','beach','linen','sand','glow'],
   ARRAY['chatgpt','gemini']::text[],
   'Photorealistic golden hour beach fashion editorial. Young woman walking barefoot along a deserted sandy beach. Wearing a lightweight flowing white linen beach pants, matching simple white linen top, tiny shell necklace. Feet in wet sand at shoreline, golden sunset reflecting in wet sand below.',
   'Golden hour beach walk editorial. White linen set flowing in sea breeze, bare feet in wet shoreline sand. Golden sunset light reflecting on sea surface and wet sand, long shadows on beach, simple and breathtaking natural beauty.',
   true),

  ('Harvest Field Golden',
   'harvest-field-golden',
   'Golden hour in a harvest wheat field — warm glow, oversized flannel, peace.',
   cat_golden,
   ARRAY['golden hour','harvest','field','wheat','warm'],
   ARRAY['mj','gemini']::text[],
   'Photorealistic golden hour in a vast golden wheat harvest field. Young man standing in tall wheat, wearing an oversized burnt-orange flannel shirt open over simple cream tee, relaxed straight jeans, worn leather boots. Sunset blazing behind, entire field lit golden, warm peaceful atmosphere.',
   'Golden harvest field fashion. Oversized burnt-orange flannel, cream tee, straight jeans, leather boots. Standing in tall golden wheat at sunset. Entire scene bathed in deep golden light, warm cinematic mood, peaceful harvest season energy.',
   true);

  -- ── NIGHT FLASH (5) ──
  INSERT INTO public.prompts (title,slug,description,category_id,tags,ai_models,prompt_chatgpt,prompt_gemini,published) VALUES
  ('Club Night Flash Portrait',
   'club-night-flash-portrait',
   'Direct flash portrait at a club night — glossy skin, micro dress, energy.',
   cat_nightflash,
   ARRAY['night flash','club','portrait','direct flash','glossy'],
   ARRAY['chatgpt','mj']::text[],
   'Disposable camera style direct flash portrait at a club night. Young woman in a glossy black mini dress, layered silver necklaces, smoky eye makeup, glossy lip. Direct flash illuminating face and creating harsh shadows behind. Dark club background with colored light bleed. High contrast, washed face, authentic party photo energy.',
   'Club night direct flash portrait. Black mini dress, layered silver chains, heavy makeup. Harsh direct flash washing face, deep shadows behind. Club lights bleeding in background. Disposable party cam aesthetic, washed and overexposed face, high energy.',
   true),

  ('Street Night Flash',
   'street-night-flash',
   'Night street flash photo — leather jacket, wet pavement, overexposed glow.',
   cat_nightflash,
   ARRAY['night flash','street','leather jacket','wet','overexposed'],
   ARRAY['chatgpt','grok']::text[],
   'Disposable camera style night street flash photo. Young person in a black leather biker jacket, black jeans, chunky boots. Caught mid-laugh in a night street scene, direct flash washing them in white light. Wet pavement reflecting city lights behind, harsh shadow on ground, authentic nightlife candid.',
   'Night street flash candid. Black leather jacket, black jeans, chunky boots, mid-laugh candid pose. Harsh direct flash overexposure, wet city street reflections behind, car light streaks, dark night sky. Raw authentic nightlife energy.',
   true),

  ('House Party Flash',
   'house-party-flash',
   'House party direct flash — drinks in hand, colorful outfits, chaotic background.',
   cat_nightflash,
   ARRAY['night flash','house party','drinks','candid','chaotic'],
   ARRAY['chatgpt','gemini']::text[],
   'Disposable camera style house party flash photo. Group of three young friends in colorful outfits holding drinks, caught laughing mid-photo. Direct flash creating washed faces and dark background. Party chaos visible behind — people, red cups, string lights. Authentic house party disposable cam energy.',
   'House party disposable flash. Three friends in colorful fits holding drinks, laughing, mid-candid. Harsh direct flash, washed bright faces, chaotic dark background of party people and colored lights. Classic house party photo energy.',
   true),

  ('After Party Exit Flash',
   'after-party-exit-flash',
   'Post-club exit flash photo — heels in hand, makeup smeared, but still stunning.',
   cat_nightflash,
   ARRAY['night flash','after party','heels','smeared','candid'],
   ARRAY['chatgpt','flux']::text[],
   'Disposable camera style direct flash candid of a woman exiting a club at 3am. Sparkly mini dress slightly wrinkled, heels in one hand, smeared eye makeup, messy hair but confident smile. Flash washing the scene, dark parking lot or street behind, another person blurred in background.',
   'After party exit flash candid. Sparkly dress, heels in hand, smeared makeup, perfect messy hair, confident grin at 3am. Direct harsh flash, dark parking lot behind, someone else blurred. Raw authentic post-night-out energy, beautiful chaos.',
   true),

  ('Rooftop Party Golden Flash',
   'rooftop-party-golden-flash',
   'Rooftop party flash with city skyline glittering behind — sequins and night energy.',
   cat_nightflash,
   ARRAY['night flash','rooftop','skyline','sequins','party'],
   ARRAY['chatgpt','mj']::text[],
   'Disposable camera style direct flash photo at a rooftop party. Young woman in a gold sequin slip dress, minimal jewelry, hair down. Direct flash lighting her face, city skyline with thousands of lights glittering behind her in the dark. Perfect contrast of harsh flash face and magical city background.',
   'Rooftop party flash portrait. Gold sequin slip dress, city skyline glittering behind. Harsh direct flash illuminating face against the dark sky and distant sparkling city lights. Iconic rooftop party night flash photo, glamour meets candid.',
   true);

END $$;
